---
- hosts: localhost
  connection: local

  tasks: 
  - name: Launch EC2 Instance
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "aws-key"
      instance_type: t2.micro
      security_group: default
      region: us-east-1
      aws_access_key: "{{ ec2_access_key }}" #From another variable file (ansible vault)
      aws_secret_key: "{{ ec2_secret_key }}" #From another variable file (ansible vault)
      network:
        assign_public_ip: true
      image_id: "{{ item.image_id }}"
      tags:
        Name: "{{ item.name }}" 
    loop:
      - { image_id: ami-04b70fa74e45c3917, name: "manage-node-1" }
      - { image_id: ami-0c55b159cbfafe1f0, name: "manage-node-2" }
      - { image_id: ami-0c55b159cbfafe1f0, name: "manage-node-3" }
      
